server {
  listen 80;
  root /usr/share/nginx/html;
  location / { try_files $uri /index.html; }
  location /api/ { proxy_pass http://concierge-api:4020/; proxy_buffering off; proxy_read_timeout 3600s; }
}
