import { useEffect, useRef, useState, type ReactNode } from "react";
import { API_BASE, type Lang } from "../lib/api";

export type DemoFilm = { hoCode: string; title: string; titleAlt?: string; posterUrl?: string; rating?: string; language?: string; status?: string; runTime?: number };
type Cinema = { cinemaId: string; name: string; nameAlt?: string };
export function filterDemoFilms(films: DemoFilm[], status: string, language: string, query: string): DemoFilm[] {
  const needle = query.trim().toLocaleLowerCase();
  return films.filter((film) => (status === "coming_soon" ? film.status === "coming_soon" || film.status === "advance" : !film.status || film.status === "now_showing") && (!language || film.language === language) && (!needle || `${film.title} ${film.titleAlt ?? ""}`.toLocaleLowerCase().includes(needle)));
}

/** Local React presentation of the public VOX reference page. No host scripts are executed. */
export function CinemaPage({ lang, onLanguage, customerName, authBusy, onAccount, children }: { lang: Lang; onLanguage: (lang: Lang) => void; customerName?: string; authBusy?: boolean; onAccount: () => void; children: ReactNode }) {
  const [films, setFilms] = useState<DemoFilm[]>([]);
  const [cinemas, setCinemas] = useState<Cinema[]>([]);
  const [status, setStatus] = useState("now_showing");
  const [filmLanguage, setFilmLanguage] = useState("");
  const [query, setQuery] = useState("");
  const [selectedMovie, setSelectedMovie] = useState("");
  const [selectedCinema, setSelectedCinema] = useState("");
  const [showAll, setShowAll] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);
  const ar = lang === "ar";
  const txt = (en: string, arabic: string) => ar ? arabic : en;
  const title = (film: DemoFilm) => ar ? film.titleAlt || film.title : film.title;
  const ask = (message: string) => window.dispatchEvent(new CustomEvent("voxi:open", { detail: { message } }));
  useEffect(() => {
    const controller = new AbortController();
    void fetch(`${API_BASE}/demo/films?status=all`, { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error("catalogue"); return response.json(); }).then((data) => { if (!controller.signal.aborted) { setFilms(Array.isArray(data.films) ? data.films : []); setFailed(false); } }).catch(() => { if (!controller.signal.aborted) setFailed(true); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    void fetch(`${API_BASE}/demo/cinemas`, { signal: controller.signal }).then((response) => response.ok ? response.json() : { cinemas: [] }).then((data) => { if (!controller.signal.aborted) setCinemas(Array.isArray(data.cinemas) ? data.cinemas : []); }).catch(() => undefined);
    return () => controller.abort();
  }, []);
  useEffect(() => { if (searchOpen) searchRef.current?.focus(); }, [searchOpen]);
  const languages = [...new Set(filterDemoFilms(films, status, "", "").map((film) => film.language).filter((value): value is string => !!value))].sort();
  const visible = filterDemoFilms(films, status, filmLanguage, query);
  const showtimes = (film?: DemoFilm) => ask(ar ? `أرني مواعيد عرض ${film ? title(film) : "الأفلام المتاحة"}` : `Show me ${film ? `showtimes for ${film.title}` : "available movie showtimes"}`);
  const findTimes = () => {
    const film = films.find((item) => item.hoCode === selectedMovie);
    const cinema = cinemas.find((item) => item.cinemaId === selectedCinema);
    ask(ar ? `أرني مواعيد ${film ? `فيلم ${title(film)}` : "الأفلام المتاحة"}${cinema ? ` في ${cinema.nameAlt || cinema.name}` : ""}` : `Show me ${film ? `showtimes for ${film.title}` : "available movie showtimes"}${cinema ? ` at ${cinema.name}` : ""}`);
  };
  const nav = [{ id: "movies", en: "MOVIES", ar: "الأفلام" }, { id: "food", en: "FOOD & DRINKS", ar: "المأكولات والمشروبات" }, { id: "experiences", en: "WAYS TO WATCH", ar: "تجارب المشاهدة" }, { id: "offers", en: "OFFERS", ar: "العروض" }, { id: "cinemas", en: "FIND US", ar: "مواقعنا" }];
  return <div className="cinema-site vox-assistant-root" data-voxi-theme="navy">
    <div className="site-brand-line" />
    <header className="site-header"><div className="site-header-inner"><a className="site-brand" href="#" aria-label={txt("VOX Cinemas home", "الصفحة الرئيسية لفوكس سينما")}><span className="vox-symbol" aria-hidden="true"><i /><i /><i /></span><span className="brand-lockup"><strong>VOX</strong><small>CINEMAS</small></span></a><nav className={`site-nav ${menuOpen ? "is-open" : ""}`} aria-label={txt("Main navigation", "التنقل الرئيسي")}>{nav.map((item) => <a href={`#${item.id}`} key={item.id} onClick={() => setMenuOpen(false)}>{ar ? item.ar : item.en}</a>)}</nav><div className="site-header-actions"><button className="site-search-button" type="button" aria-label={txt("Search movies", "البحث عن الأفلام")} aria-expanded={searchOpen} onClick={() => setSearchOpen(!searchOpen)}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 5 5" /></svg></button><button className="site-language" onClick={() => onLanguage(ar ? "en" : "ar")}>{ar ? "English" : "العربية"}</button><button className="site-signin" disabled={authBusy} onClick={onAccount}>{customerName ?? txt("Sign in", "تسجيل الدخول")}</button><button className="site-menu" aria-label={txt("Menu", "القائمة")} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>☰</button></div></div>{searchOpen ? <div className="site-search"><label htmlFor="site-movie-search">{txt("Find your next movie", "ابحث عن فيلمك القادم")}</label><input id="site-movie-search" ref={searchRef} type="search" value={query} placeholder={txt("Search movie titles", "ابحث عن اسم الفيلم")} onChange={(event) => { setQuery(event.target.value); setShowAll(true); }} /><a href="#movies">{txt("See results", "عرض النتائج")} ↓</a></div> : null}</header>
    <section className="site-booking-bar" id="booking"><div className="site-booking-inner"><label><span>{txt("SELECT YOUR CINEMA(S)", "اختر السينما")}</span><select value={selectedCinema} onChange={(event) => setSelectedCinema(event.target.value)}><option value="">{txt("Select Your Cinema(s)", "اختر السينما")}</option>{cinemas.map((cinema) => <option key={cinema.cinemaId} value={cinema.cinemaId}>{ar ? cinema.nameAlt || cinema.name : cinema.name}</option>)}</select></label><label><span>{txt("SELECT YOUR MOVIE(S)", "اختر الفيلم")}</span><select value={selectedMovie} onChange={(event) => setSelectedMovie(event.target.value)}><option value="">{txt("Any Movie", "أي فيلم")}</option>{filterDemoFilms(films, "now_showing", "", "").map((film) => <option key={film.hoCode} value={film.hoCode}>{title(film)}</option>)}</select></label><button className="site-blue-button" onClick={findTimes}>{txt("FIND TIMES AND BOOK", "اعرض المواعيد واحجز")}</button></div></section>
    <main>
      <section className="site-hero"><div className="site-hero-inner"><div className="site-hero-copy"><span className="site-hero-kicker">{txt("ON THE BIG SCREEN", "على الشاشة الكبيرة")}</span><h1>{ar ? <>رحلة <span>الأوديسة</span></> : <>THE <span>ODYSSEY</span></>}</h1><div className="site-hero-meta"><span>15+</span><i /><span>{txt("EPIC ADVENTURE", "مغامرة ملحمية")}</span><i /><span>IMAX</span></div><p>{txt("Experience Christopher Nolan's epic adventure on the big screen.", "استمتع بمغامرة كريستوفر نولان الملحمية على الشاشة الكبيرة.")}</p><div className="site-hero-buttons"><button className="site-blue-button" onClick={() => ask(txt("Show me available showtimes for The Odyssey", "أرني مواعيد عرض فيلم The Odyssey المتاحة"))}>{txt("BOOK NOW", "احجز الآن")}</button><a className="site-outline-button" href="#movies">{txt("VIEW MOVIES", "عرض الأفلام")}</a></div><div className="site-carousel-dots" aria-hidden="true"><i className="active" /><i /><i /><i /></div></div><div className="site-hero-visual" aria-hidden="true"><div className="site-hero-glow" /><img src="https://voxi.kris-pradip.workers.dev/assets/odyssey.png" alt="" /></div></div></section>
      <section className="site-movies-section" id="movies"><div className="site-section-shell"><div className="site-section-heading"><h2>{txt("What's On", "ماذا يُعرض؟")}</h2><div className="site-movie-tabs" role="tablist" aria-label={txt("Movie schedule", "جدول الأفلام")}>{[{ value: "now_showing", en: "NOW SHOWING", ar: "يُعرض الآن" }, { value: "coming_soon", en: "COMING SOON", ar: "قريباً" }].map((tab) => <button key={tab.value} role="tab" aria-selected={status === tab.value} onClick={() => { setStatus(tab.value); setFilmLanguage(""); setShowAll(false); }}>{ar ? tab.ar : tab.en}</button>)}</div></div>{languages.length ? <div className="site-movie-filters" aria-label={txt("Movie language", "لغة الفيلم")}><button className={!filmLanguage ? "active" : ""} aria-pressed={!filmLanguage} onClick={() => setFilmLanguage("")}>{txt("ALL", "الكل")}</button>{languages.map((language) => <button className={filmLanguage === language ? "active" : ""} key={language} aria-pressed={filmLanguage === language} onClick={() => setFilmLanguage(language)}>{language}</button>)}</div> : null}{query ? <p className="site-filter-summary">{txt("Results for", "نتائج البحث عن")} “{query}” <button onClick={() => setQuery("")}>{txt("Clear", "مسح")}</button></p> : null}<div className="site-movie-grid" aria-busy={loading}>{visible.slice(0, showAll ? visible.length : 8).map((film) => <article className="site-movie-card" key={film.hoCode}><button className="site-poster-button" aria-label={`${txt("Showtimes for", "مواعيد عرض")} ${title(film)}`} onClick={() => showtimes(film)}>{film.posterUrl ? <img src={film.posterUrl} alt="" loading="lazy" /> : <span className="site-poster-placeholder">VOX</span>}{film.rating ? <span className="site-rating">{film.rating}</span> : null}</button><div className="site-movie-info"><h3>{title(film)}</h3><p>{[film.language, film.runTime ? `${film.runTime} ${txt("mins", "دقيقة")}` : ""].filter(Boolean).join(" · ") || "VOX Cinemas"}</p><button onClick={() => showtimes(film)}>{txt("BOOK NOW", "احجز الآن")} <span aria-hidden="true">↗</span></button></div></article>)}</div>{!visible.length ? <p className="site-empty" role="status">{loading ? txt("Loading movies…", "جارٍ تحميل الأفلام…") : failed ? txt("The movie catalogue is unavailable right now. You can still ask us about a movie.", "قائمة الأفلام غير متاحة حالياً. يمكنك سؤالنا عن الفيلم الذي تريده.") : txt("No movies match these filters.", "لا توجد أفلام تطابق هذه الخيارات.")}</p> : null}{visible.length > 8 ? <button className="site-view-all" aria-expanded={showAll} onClick={() => setShowAll(!showAll)}>{showAll ? txt("SHOW LESS", "عرض أقل") : txt("VIEW ALL", "عرض الكل")}</button> : null}</div></section>
      <section className="site-experience-section" id="experiences"><div className="site-section-shell"><div className="site-experience-heading"><h2>{txt("Try a VOX experience", "جرّب تجارب فوكس")}</h2><p>{txt("Make your next movie more than just a trip to the cinema.", "اجعل فيلمك القادم تجربة تتجاوز حدود السينما.")}</p></div><div className="site-experience-grid">{[{ name: "IMAX", tag: txt("SEE MORE", "شاهد أكثر"), copy: txt("Bigger screens. Bigger sound. Bigger movies.", "شاشات أكبر، صوت أقوى وأفلام أروع.") }, { name: "THEATRE", tag: txt("DINE IN STYLE", "تناول الطعام بأناقة"), copy: txt("Reclining seats, premium service and cinema dining.", "مقاعد قابلة للإمالة وخدمة راقية وتجربة طعام سينمائية.") }, { name: "4DX", tag: txt("FEEL THE MOVIE", "عش الفيلم"), copy: txt("Motion and environmental effects put you inside the action.", "حركة ومؤثرات تجعلك في قلب الحدث.") }, { name: "KIDS", tag: txt("MADE FOR FAMILIES", "للعائلة"), copy: txt("A colourful cinema experience for younger movie fans.", "تجربة سينمائية مليئة بالألوان لعشاق الأفلام الصغار.") }].map((experience) => <article className={`site-experience-card experience-${experience.name.toLowerCase()}`} key={experience.name}><div><span>{experience.tag}</span><h3>{experience.name}</h3><p>{experience.copy}</p><button onClick={() => ask(ar ? `أخبرني عن تجربة ${experience.name} في فوكس` : `Tell me about the ${experience.name} experience at VOX`)}>{txt("DISCOVER", "اكتشف")} {experience.name}</button></div></article>)}</div></div></section>
      <section className="site-food-section" id="food"><div className="site-food-inner"><div><span className="site-eyebrow">{txt("FOOD & DRINKS", "المأكولات والمشروبات")}</span><h2>{txt("Movie night tastes better at VOX", "ليلتك السينمائية ألذ مع فوكس")}</h2><p>{txt("Choose your cinema favourites for the perfect movie night.", "اختر مأكولاتك المفضلة لليلة سينمائية رائعة.")}</p><button className="site-blue-button" onClick={() => ask(txt("Show me the food and drinks menu", "أرني قائمة المأكولات والمشروبات"))}>{txt("ORDER FOOD ONLINE", "اطلب المأكولات")}</button></div><div className="site-food-art" aria-hidden="true"><div className="site-popcorn"><i /><i /><i /><i /><i /><strong>VOX</strong></div></div></div></section>
      <section className="site-offers-section" id="offers"><div className="site-section-shell"><div className="site-section-heading"><h2>{txt("Offers & promotions", "العروض والتخفيضات")}</h2><button className="site-text-link" onClick={() => ask(txt("Show me available offers", "أرني العروض المتاحة"))}>{txt("VIEW ALL OFFERS", "جميع العروض")} ↗</button></div><div className="site-offers-grid"><article className="site-offer-card site-share-offer"><span>SHARE</span><h3>{txt("Make every movie more rewarding", "مكافآت أكثر مع كل فيلم")}</h3><p>{txt("Earn and spend SHARE points when you enjoy VOX Cinemas.", "اكسب واستخدم نقاط شير عند الاستمتاع بفوكس سينما.")}</p><button onClick={() => ask(txt("Tell me about SHARE Points at VOX", "أخبرني عن نقاط شير في فوكس"))}>{txt("LEARN MORE", "اعرف المزيد")}</button></article><article className="site-offer-card site-food-offer"><span>{txt("FOOD & DRINKS", "المأكولات والمشروبات")}</span><h3>{txt("Pre-order your snacks", "اختر وجباتك الخفيفة")}</h3><p>{txt("Complete your movie night with your favourites.", "أكمل ليلتك السينمائية بمأكولاتك المفضلة.")}</p><button onClick={() => ask(txt("I'd like to order snacks", "أريد طلب وجبات خفيفة"))}>{txt("ORDER ONLINE", "اطلب الآن")}</button></article></div></div></section>
      <section className="site-find-section" id="cinemas"><div className="site-section-shell"><span className="site-eyebrow">{txt("FIND US", "مواقعنا")}</span><h2>{txt("Find your nearest VOX Cinema", "اعثر على أقرب سينما فوكس")}</h2><p>{txt("VOX Cinemas locations across Dubai, Abu Dhabi and the UAE.", "مواقع فوكس سينما في دبي وأبوظبي ومختلف أنحاء الإمارات.")}</p><button className="site-blue-button" onClick={() => ask(txt("Help me find a nearby VOX cinema", "ساعدني في العثور على سينما فوكس قريبة"))}>{txt("FIND A CINEMA", "ابحث عن سينما")}</button></div></section>
    </main>
    <footer className="site-footer"><div className="site-footer-inner"><div className="site-footer-brand"><strong>VOX</strong><small>CINEMAS</small><p>{txt("Great movies. Great experiences.", "أفلام رائعة. تجارب استثنائية.")}</p></div><div><b>{txt("MOVIES", "الأفلام")}</b><a href="#movies">{txt("What's On", "ماذا يُعرض؟")}</a><a href="#movies" onClick={() => { setStatus("coming_soon"); setFilmLanguage(""); }}>{txt("Coming Soon", "قريباً")}</a><a href="#booking">{txt("Book Tickets", "حجز التذاكر")}</a></div><div><b>{txt("EXPERIENCE", "التجارب")}</b>{["IMAX", "THEATRE", "4DX", "KIDS"].map((name) => <a href="#experiences" key={name}>{name}</a>)}</div><div><b>VOX CINEMAS</b><a href="#cinemas">{txt("Find Us", "مواقعنا")}</a><a href="#offers">{txt("Offers", "العروض")}</a><a href="#food">{txt("Food & Drinks", "المأكولات والمشروبات")}</a></div></div><div className="site-footer-bottom"><span>© VOX Cinemas</span><span>{txt("Demo experience · payments are simulated", "تجربة توضيحية · المدفوعات تجريبية")}</span></div></footer>
    {children}
  </div>;
}
