import type { ModifierGroup } from "../schema/commerce.js";
/** Dummy commercial catalogue: ticket types, concessions, offers, cinema extensions. Prices in fils (AED cents). */
import type { OfferBenefit, OfferRules } from "../schema/customer.js";

export type TicketTypeSpec = {
  code: string;
  description: string;
  descriptionAlt: string;
  area: "0000000002" | "0000000001" | "0000000003";
  priceInCents: number;
  isChild?: boolean;
  loyaltyOnly?: boolean;
  long?: string;
};

/**
 * Seat-tier pricing as sold on uae.voxcinemas.com: tickets are priced per seat area ("x1 Regular –
 * 46.00 AED per ticket"), with Premium and Preferred View tiers in larger screens. Observed 4 Sep 2026:
 * Standard (Deira) Regular 46; MAX (Mirdif) Regular 52 / Premium 65 / Preferred View 70.
 */
export const EXPERIENCE_PRICING: Record<
  string,
  { regular: number; premium?: number; preferred?: number; child?: number; menuTab?: string }
> = {
  Standard: { regular: 4600, premium: 5600, preferred: 6100, child: 3600 },
  MAX: { regular: 5200, premium: 6500, preferred: 7000, child: 4200 },
  IMAX: { regular: 7500, premium: 8500, preferred: 9000, child: 5500 },
  GOLD: { regular: 14500, menuTab: "GOLD Menu" },
  KIDS: { regular: 4500, child: 3500 },
  "4DX": { regular: 8500, child: 7000 },
  THEATRE: { regular: 16500, menuTab: "THEATRE Menu" },
  Premier: { regular: 6500, premium: 7500, preferred: 8000, child: 5000 },
  Premium: { regular: 7500 },
  Couch: { regular: 11000 },
  Outdoor: { regular: 9000, child: 7000 },
  Private: { regular: 25000 },
  Other: { regular: 4600, child: 3600 },
};

/** Vista area category codes used across the mock: 2 = Regular, 1 = Premium, 3 = Preferred View. */
export const AREA = { REGULAR: "0000000002", PREMIUM: "0000000001", PREFERRED: "0000000003" } as const;

export function ticketTypesFor(experience: string): TicketTypeSpec[] {
  const p = EXPERIENCE_PRICING[experience] ?? EXPERIENCE_PRICING.Standard!;
  const ex = experience.toUpperCase();
  const out: TicketTypeSpec[] = [
    {
      code: "0001",
      description: `${ex} REGULAR`,
      descriptionAlt: `${experience} عادي`,
      area: AREA.REGULAR,
      priceInCents: p.regular,
    },
  ];
  if (p.child)
    out.push({
      code: "0002",
      description: `${ex} REGULAR CHILD (3-12)`,
      descriptionAlt: `${experience} عادي طفل`,
      area: AREA.REGULAR,
      priceInCents: p.child,
      isChild: true,
    });
  if (p.premium)
    out.push({
      code: "0131",
      description: `${ex} PREMIUM`,
      descriptionAlt: `${experience} بريميوم`,
      area: AREA.PREMIUM,
      priceInCents: p.premium,
      long: "Premium seats sit in the middle block with extra legroom.",
    });
  if (p.preferred)
    out.push({
      code: "0141",
      description: `${ex} PREFERRED VIEW`,
      descriptionAlt: `${experience} بريفيرد فيو`,
      area: AREA.PREFERRED,
      priceInCents: p.preferred,
      long: "Preferred View seats are the back rows with the best sightline.",
    });
  out.push({
    code: "0090",
    description: `${ex} REGULAR SHARE MEMBER`,
    descriptionAlt: `${experience} عادي عضو شير`,
    area: AREA.REGULAR,
    priceInCents: Math.round(p.regular * 0.9),
    loyaltyOnly: true,
    long: "SHARE members save 10% on Regular seats. Log in to redeem.",
  });
  return out;
}

export type ConcessionSpec = {
  id: string;
  tab: string;
  description: string;
  descriptionAlt: string;
  extended: string;
  price: number;
  dietary: string[];
  allergens?: string[];
  calories?: number;
  isCombo?: boolean;
  children?: { itemId: string; quantity: number }[];
  modifiers?: ModifierGroup[];
  experiences?: string[];
  bestSeller?: boolean;
  image: string;
};

/**
 * Real City Centre Deira menu (uae.voxcinemas.com booking flow, 4 Sep 2026): names, prices, categories and
 * image URLs are genuine; dietary tags are inferred from names; GOLD/THEATRE items are demo-only.
 */
export const CONCESSIONS: ConcessionSpec[] = [
  {
    id: "8610",
    tab: "Popcorn",
    description: "Large mix standard popcorn",
    descriptionAlt: "فشار — Large mix standard popcorn",
    extended: "",
    price: 2600,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_12805.png",
  },
  {
    id: "2346",
    tab: "Popcorn",
    description: "Cheese popcorn",
    descriptionAlt: "فشار — Cheese popcorn",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3820.png",
    modifiers: [
      {
        name: "Size",
        required: true,
        options: [
          {
            id: "L",
            name: "Large",
            priceInCents: 200,
          },
          {
            id: "R",
            name: "Regular",
            priceInCents: 0,
          },
          {
            id: "S",
            name: "Small",
            priceInCents: -300,
          },
        ],
      },
    ],
    bestSeller: true,
  },
  {
    id: "2461",
    tab: "Popcorn",
    description: "Salt popcorn",
    descriptionAlt: "فشار — Salt popcorn",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3818.png",
    modifiers: [
      {
        name: "Size",
        required: true,
        options: [
          {
            id: "L",
            name: "Large",
            priceInCents: 200,
          },
          {
            id: "R",
            name: "Regular",
            priceInCents: 0,
          },
          {
            id: "S",
            name: "Small",
            priceInCents: -300,
          },
        ],
      },
    ],
    bestSeller: true,
  },
  {
    id: "2288",
    tab: "Popcorn",
    description: "Caramel popcorn",
    descriptionAlt: "فشار — Caramel popcorn",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3819.png",
    modifiers: [
      {
        name: "Size",
        required: true,
        options: [
          {
            id: "L",
            name: "Large",
            priceInCents: 200,
          },
          {
            id: "R",
            name: "Regular",
            priceInCents: 0,
          },
          {
            id: "S",
            name: "Small",
            priceInCents: -300,
          },
        ],
      },
    ],
  },
  {
    id: "10159",
    tab: "Popcorn",
    description: "Movie Time Box",
    descriptionAlt: "فشار — Movie Time Box",
    extended: "",
    price: 3500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_13252_1762857742295.png",
  },
  {
    id: "8609",
    tab: "Popcorn",
    description: "Regular mix standard popcorn",
    descriptionAlt: "فشار — Regular mix standard popcorn",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_12804.png",
  },
  {
    id: "4415",
    tab: "Popcorn",
    description: "Large Cheetos Popcorn Flaming",
    descriptionAlt: "فشار — Large Cheetos Popcorn Flaming",
    extended: "",
    price: 3200,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_5476_1747211371135.jpg",
    bestSeller: true,
  },
  {
    id: "10330",
    tab: "Popcorn",
    description: "Large Pringles Sour Cream & Onion Popcorn",
    descriptionAlt: "فشار — Large Pringles Sour Cream & Onion Popcorn",
    extended: "",
    price: 3200,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_15665_1722233268652.png",
  },
  {
    id: "8608",
    tab: "Popcorn",
    description: "Regular mix premium popcorn",
    descriptionAlt: "فشار — Regular mix premium popcorn",
    extended: "",
    price: 3000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_12803_1736687462495.jpg",
  },
  {
    id: "7052",
    tab: "Popcorn",
    description: "Large cheetos popcorn crunchy",
    descriptionAlt: "فشار — Large cheetos popcorn crunchy",
    extended: "",
    price: 3200,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_10143.png",
  },
  {
    id: "4416",
    tab: "Popcorn",
    description: "Regular Cheetos Popcorn Flaming",
    descriptionAlt: "فشار — Regular Cheetos Popcorn Flaming",
    extended: "",
    price: 3000,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_5477_1747211341725.jpg",
  },
  {
    id: "10333",
    tab: "Popcorn",
    description: "Regular Pringles Sour Cream & Onion Popcorn",
    descriptionAlt: "فشار — Regular Pringles Sour Cream & Onion Popcorn",
    extended: "",
    price: 3000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_15664_1722233287475.png",
  },
  {
    id: "4417",
    tab: "Popcorn",
    description: "Regular Cheetos Popcorn Crunchy",
    descriptionAlt: "فشار — Regular Cheetos Popcorn Crunchy",
    extended: "",
    price: 3000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_5478_1747211286561.jpg",
  },
  {
    id: "10936",
    tab: "Hot Drinks",
    description: "Saffron Karak tea",
    descriptionAlt: "مشروب ساخن — Saffron Karak tea",
    extended: "",
    price: 700,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_16768_1756120183764.png",
  },
  {
    id: "3000",
    tab: "Hot Drinks",
    description: "Latte",
    descriptionAlt: "مشروب ساخن — Latte",
    extended: "",
    price: 1800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_5017_1743187764986.png",
  },
  {
    id: "2999",
    tab: "Hot Drinks",
    description: "Cappuccino",
    descriptionAlt: "مشروب ساخن — Cappuccino",
    extended: "",
    price: 1800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_5016_1743187383146.png",
  },
  {
    id: "2998",
    tab: "Hot Drinks",
    description: "Americano",
    descriptionAlt: "مشروب ساخن — Americano",
    extended: "",
    price: 1600,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_5015_1743187062028.png",
  },
  {
    id: "2516",
    tab: "Hot Drinks",
    description: "Hot Tea",
    descriptionAlt: "مشروب ساخن — Hot Tea",
    extended: "",
    price: 1600,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3995_1743187986675.png",
  },
  {
    id: "3001",
    tab: "Hot Drinks",
    description: "Single espresso",
    descriptionAlt: "مشروب ساخن — Single espresso",
    extended: "",
    price: 1200,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_5018_1743187653465.png",
  },
  {
    id: "3002",
    tab: "Hot Drinks",
    description: "Double espresso",
    descriptionAlt: "مشروب ساخن — Double espresso",
    extended: "",
    price: 1600,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_5019_1743187432438.png",
  },
  {
    id: "7747",
    tab: "Combos",
    description: "Regular Popcorn and Drink Combo",
    descriptionAlt: "كومبو — Regular Popcorn and Drink Combo",
    extended: "",
    price: 3700,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_10995.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
    bestSeller: true,
  },
  {
    id: "9540",
    tab: "Combos",
    description: "Large Popcorn and Drink Combo",
    descriptionAlt: "كومبو — Large Popcorn and Drink Combo",
    extended: "",
    price: 4200,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_14847.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
    bestSeller: true,
  },
  {
    id: "9542",
    tab: "Combos",
    description: "Nachos Deluxe and Large Drink Combo",
    descriptionAlt: "كومبو — Nachos Deluxe and Large Drink Combo",
    extended: "",
    price: 6000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_14850.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "9538",
    tab: "Combos",
    description: "Nachos Supreme And Regular Drink Combo",
    descriptionAlt: "كومبو — Nachos Supreme And Regular Drink Combo",
    extended: "",
    price: 5000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_12680.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "3043",
    tab: "Combos",
    description: "Large Hotdog Combo",
    descriptionAlt: "كومبو — Large Hotdog Combo",
    extended: "",
    price: 6600,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_4942.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "3041",
    tab: "Combos",
    description: "Regular Hotdog Combo",
    descriptionAlt: "كومبو — Regular Hotdog Combo",
    extended: "",
    price: 6100,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_4940.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "9543",
    tab: "Combos",
    description: "Large Burger Combo",
    descriptionAlt: "كومبو — Large Burger Combo",
    extended: "",
    price: 6600,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14853.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "9545",
    tab: "Combos",
    description: "Regular Burger Combo",
    descriptionAlt: "كومبو — Regular Burger Combo",
    extended: "",
    price: 6100,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14852.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "9730",
    tab: "Combos",
    description: "Kids Meal Box",
    descriptionAlt: "كومبو — Kids Meal Box",
    extended: "",
    price: 4000,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_15148.png",
    isCombo: true,
    modifiers: [
      {
        name: "Drink",
        required: true,
        options: [
          {
            id: "PEPSI",
            name: "Pepsi",
            priceInCents: 0,
          },
          {
            id: "DIET",
            name: "Diet Pepsi",
            priceInCents: 0,
          },
          {
            id: "7UP",
            name: "7 Up",
            priceInCents: 0,
          },
          {
            id: "MIRINDA",
            name: "Mirinda",
            priceInCents: 0,
          },
          {
            id: "DEW",
            name: "Mountain Dew",
            priceInCents: 0,
          },
          {
            id: "WATER",
            name: "Water",
            priceInCents: 0,
          },
        ],
      },
    ],
  },
  {
    id: "2482",
    tab: "Soda",
    description: "Regular pepsi",
    descriptionAlt: "مشروب غازي — Regular pepsi",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/a9e776d8-c806-4929-8c34-8a0f243853f2.jpg",
    bestSeller: true,
  },
  {
    id: "5224",
    tab: "Soda",
    description: "Fruit slush regular",
    descriptionAlt: "مشروب غازي — Fruit slush regular",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_4751_1783926996639.jpg",
  },
  {
    id: "2385",
    tab: "Soda",
    description: "Large Pepsi",
    descriptionAlt: "مشروب غازي — Large Pepsi",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3784.jpg",
  },
  {
    id: "2427",
    tab: "Soda",
    description: "Slush pepsi",
    descriptionAlt: "مشروب غازي — Slush pepsi",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3821_1743073380312.jpg",
  },
  {
    id: "2275",
    tab: "Soda",
    description: "Slush Mountain Dew",
    descriptionAlt: "مشروب غازي — Slush Mountain Dew",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3825_1743073194399.jpg",
  },
  {
    id: "2489",
    tab: "Soda",
    description: "Regular Diet/ Black Pepsi",
    descriptionAlt: "مشروب غازي — Regular Diet/ Black Pepsi",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3786.jpg",
  },
  {
    id: "2508",
    tab: "Soda",
    description: "Regular Mountain Dew",
    descriptionAlt: "مشروب غازي — Regular Mountain Dew",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3788.jpg",
  },
  {
    id: "2274",
    tab: "Soda",
    description: "Slush Mirinda",
    descriptionAlt: "مشروب غازي — Slush Mirinda",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3823_1743073255658.jpg",
  },
  {
    id: "2504",
    tab: "Soda",
    description: "Regular 7 Up",
    descriptionAlt: "مشروب غازي — Regular 7 Up",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3785.jpg",
  },
  {
    id: "2329",
    tab: "Soda",
    description: "Large Mountain Dew",
    descriptionAlt: "مشروب غازي — Large Mountain Dew",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3783.jpg",
  },
  {
    id: "2359",
    tab: "Soda",
    description: "Regular Mirinda",
    descriptionAlt: "مشروب غازي — Regular Mirinda",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3787.jpg",
  },
  {
    id: "2503",
    tab: "Soda",
    description: "Large 7 Up",
    descriptionAlt: "مشروب غازي — Large 7 Up",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3780.jpg",
  },
  {
    id: "2354",
    tab: "Soda",
    description: "Regular Lipton Peach",
    descriptionAlt: "مشروب غازي — Regular Lipton Peach",
    extended: "",
    price: 2200,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3802.jpeg",
  },
  {
    id: "2350",
    tab: "Soda",
    description: "Regular Lipton Lemon",
    descriptionAlt: "مشروب غازي — Regular Lipton Lemon",
    extended: "",
    price: 2200,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3805.jpeg",
  },
  {
    id: "2488",
    tab: "Soda",
    description: "Large Diet/ Black Pepsi",
    descriptionAlt: "مشروب غازي — Large Diet/ Black Pepsi",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3781.jpg",
  },
  {
    id: "2358",
    tab: "Soda",
    description: "Large Mirinda",
    descriptionAlt: "مشروب غازي — Large Mirinda",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3782.jpg",
  },
  {
    id: "2291",
    tab: "Nachos",
    description: "Nachos deluxe",
    descriptionAlt: "ناتشوز — Nachos deluxe",
    extended: "",
    price: 4500,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3844_1743538124785.jpg",
    bestSeller: true,
  },
  {
    id: "9728",
    tab: "Nachos",
    description: "Masala Nachos",
    descriptionAlt: "ناتشوز — Masala Nachos",
    extended: "",
    price: 3100,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_15145_1743538067793.jpg",
  },
  {
    id: "9729",
    tab: "Nachos",
    description: "Chicken Masala Nachos",
    descriptionAlt: "ناتشوز — Chicken Masala Nachos",
    extended: "",
    price: 4100,
    dietary: ["spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_15147.png",
  },
  {
    id: "10414",
    tab: "Nachos",
    description: "Premium Nachos",
    descriptionAlt: "ناتشوز — Premium Nachos",
    extended: "",
    price: 5900,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_15837_1743538221209.jpg",
  },
  {
    id: "2660",
    tab: "Nachos",
    description: "Extra Rico Gourmet Cheese",
    descriptionAlt: "ناتشوز — Extra Rico Gourmet Cheese",
    extended: "",
    price: 500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4347_1748943007805.jpg",
  },
  {
    id: "10626",
    tab: "Nachos",
    description: "Add Guacamole for Nachos",
    descriptionAlt: "ناتشوز — Add Guacamole for Nachos",
    extended: "",
    price: 1100,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_13407_1743537791783.jpg",
  },
  {
    id: "2662",
    tab: "Nachos",
    description: "Extra Jalapeno",
    descriptionAlt: "ناتشوز — Extra Jalapeno",
    extended: "",
    price: 500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4349_1743537867428.jpg",
  },
  {
    id: "2659",
    tab: "Nachos",
    description: "Extra Rico Chunky Salsa",
    descriptionAlt: "ناتشوز — Extra Rico Chunky Salsa",
    extended: "",
    price: 500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4346_1748943055992.jpg",
  },
  {
    id: "10627",
    tab: "Nachos",
    description: "Add Chili Con Carne for Nachos",
    descriptionAlt: "ناتشوز — Add Chili Con Carne for Nachos",
    extended: "",
    price: 1300,
    dietary: ["gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_13447_1743537751923.jpg",
  },
  {
    id: "9396",
    tab: "Cinema Snack",
    description: "Vegetable Samosa 1 PC",
    descriptionAlt: "وجبة خفيفة — Vegetable Samosa 1 PC",
    extended: "",
    price: 500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_14670_1759151008789.jpg",
  },
  {
    id: "9397",
    tab: "Cinema Snack",
    description: "Chicken Samosa 1 PC",
    descriptionAlt: "وجبة خفيفة — Chicken Samosa 1 PC",
    extended: "",
    price: 500,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14671_1759151162725.jpg",
  },
  {
    id: "10646",
    tab: "Cinema Snack",
    description: "Chicken 65 Wrap",
    descriptionAlt: "وجبة خفيفة — Chicken 65 Wrap",
    extended: "",
    price: 1700,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_16279_1758874386379.jpg",
  },
  {
    id: "9528",
    tab: "Cinema Snack",
    description: "Large Chicken Popcorn",
    descriptionAlt: "وجبة خفيفة — Large Chicken Popcorn",
    extended: "",
    price: 3200,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14833_1743537335731.jpg",
    bestSeller: true,
  },
  {
    id: "10544",
    tab: "Cinema Snack",
    description: "Chicken Cutlet 1 PC",
    descriptionAlt: "وجبة خفيفة — Chicken Cutlet 1 PC",
    extended: "",
    price: 600,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_15951_1760084784702.png",
  },
  {
    id: "9534",
    tab: "Cinema Snack",
    description: "Large Spicy Masala Chicken Popcorn",
    descriptionAlt: "وجبة خفيفة — Large Spicy Masala Chicken Popcorn",
    extended: "",
    price: 3300,
    dietary: ["spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_14839.png",
  },
  {
    id: "11061",
    tab: "Cinema Snack",
    description: "Chicken Momos",
    descriptionAlt: "وجبة خفيفة — Chicken Momos",
    extended: "",
    price: 2000,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_10982_1756108684598.png",
  },
  {
    id: "5234",
    tab: "Cinema Snack",
    description: "Masala Sweet Corn",
    descriptionAlt: "وجبة خفيفة — Masala Sweet Corn",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_6145.png",
  },
  {
    id: "5824",
    tab: "Cinema Snack",
    description: "Veg Cutlet 1 PC",
    descriptionAlt: "وجبة خفيفة — Veg Cutlet 1 PC",
    extended: "",
    price: 600,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4529_1759150829806.jpg",
  },
  {
    id: "5233",
    tab: "Cinema Snack",
    description: "Plain Sweet Corn",
    descriptionAlt: "وجبة خفيفة — Plain Sweet Corn",
    extended: "",
    price: 2100,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_6144.png",
  },
  {
    id: "5933",
    tab: "Cinema Snack",
    description: "Vada pav",
    descriptionAlt: "وجبة خفيفة — Vada pav",
    extended: "",
    price: 2300,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_8220.jpg",
  },
  {
    id: "10342",
    tab: "Cinema Snack",
    description: "Vegetable Spring Roll 1 PC",
    descriptionAlt: "وجبة خفيفة — Vegetable Spring Roll 1 PC",
    extended: "",
    price: 700,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_8211.jpg",
  },
  {
    id: "10647",
    tab: "Cinema Snack",
    description: "Paneer Tikka Wrap",
    descriptionAlt: "وجبة خفيفة — Paneer Tikka Wrap",
    extended: "",
    price: 1700,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_16280_1758874178078.jpg",
  },
  {
    id: "11059",
    tab: "Cinema Snack",
    description: "Vegetable Momos",
    descriptionAlt: "وجبة خفيفة — Vegetable Momos",
    extended: "",
    price: 1800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_10979_1756108664565.png",
  },
  {
    id: "5900",
    tab: "Cinema Snack",
    description: "Chicken Spring Roll 1 PC Chaat Counter",
    descriptionAlt: "وجبة خفيفة — Chicken Spring Roll 1 PC Chaat Counter",
    extended: "",
    price: 700,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_8540_1759150719223.jpg",
  },
  {
    id: "5942",
    tab: "Cinema Snack",
    description: "Samosa pav",
    descriptionAlt: "وجبة خفيفة — Samosa pav",
    extended: "",
    price: 2300,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_8219.jpg",
  },
  {
    id: "1715",
    tab: "Fries",
    description: "Spicy masala fries",
    descriptionAlt: "بطاطس — Spicy masala fries",
    extended: "",
    price: 1600,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_3074.png",
  },
  {
    id: "2402",
    tab: "Fries",
    description: "Signature Fries",
    descriptionAlt: "بطاطس — Signature Fries",
    extended: "",
    price: 1400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3866_1743537601311.jpg",
    bestSeller: true,
  },
  {
    id: "4881",
    tab: "Fries",
    description: "Kamikaze Dynamite Loaded Fries",
    descriptionAlt: "بطاطس — Kamikaze Dynamite Loaded Fries",
    extended: "",
    price: 2400,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_6927_1743537268159.jpg",
  },
  {
    id: "1053",
    tab: "Cold Drinks",
    description: "Acqua Panna 500ml",
    descriptionAlt: "مشروب بارد — Acqua Panna 500ml",
    extended: "",
    price: 1400,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_1693.jpg",
  },
  {
    id: "2411",
    tab: "Cold Drinks",
    description: "Redbull regular",
    descriptionAlt: "مشروب بارد — Redbull regular",
    extended: "",
    price: 2000,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_3721_1743071898204.jpg",
  },
  {
    id: "2419",
    tab: "Cold Drinks",
    description: "Aquafina",
    descriptionAlt: "مشروب بارد — Aquafina",
    extended: "",
    price: 700,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3661.jpg",
  },
  {
    id: "10165",
    tab: "Cold Drinks",
    description: "Lipton Peach Zero Sugar 320ml",
    descriptionAlt: "مشروب بارد — Lipton Peach Zero Sugar 320ml",
    extended: "",
    price: 1200,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_12582.jpeg",
  },
  {
    id: "10166",
    tab: "Cold Drinks",
    description: "Lipton Lemon Zero Sugar 320ml",
    descriptionAlt: "مشروب بارد — Lipton Lemon Zero Sugar 320ml",
    extended: "",
    price: 1200,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_13245.png",
  },
  {
    id: "2412",
    tab: "Cold Drinks",
    description: "Redbull Sugar free",
    descriptionAlt: "مشروب بارد — Redbull Sugar free",
    extended: "",
    price: 2000,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3722_1743071913141.png",
  },
  {
    id: "2417",
    tab: "Cold Drinks",
    description: "San Pellegrino 500ml",
    descriptionAlt: "مشروب بارد — San Pellegrino 500ml",
    extended: "",
    price: 1700,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_3597.jpg",
  },
  {
    id: "10182",
    tab: "Cold Drinks",
    description: "Lipton Tropical Zero Sugar 320ml",
    descriptionAlt: "مشروب بارد — Lipton Tropical Zero Sugar 320ml",
    extended: "",
    price: 1200,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/C_13267.png",
  },
  {
    id: "4884",
    tab: "Hotdogs",
    description: "New York Chicken Hotdog",
    descriptionAlt: "هوت دوغ — New York Chicken Hotdog",
    extended: "",
    price: 2800,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_6923.jpg",
  },
  {
    id: "5297",
    tab: "Hotdogs",
    description: "New York Beef Hotdog",
    descriptionAlt: "هوت دوغ — New York Beef Hotdog",
    extended: "",
    price: 2800,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_6696_1743537421469.jpg",
  },
  {
    id: "9525",
    tab: "Hotdogs",
    description: "Tikka Beef Hotdog",
    descriptionAlt: "هوت دوغ — Tikka Beef Hotdog",
    extended: "",
    price: 3000,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14830.png",
  },
  {
    id: "8581",
    tab: "Burgers",
    description: "Classic Beef Cheese Burger",
    descriptionAlt: "برغر — Classic Beef Cheese Burger",
    extended: "",
    price: 2900,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_12587_1743537038822.jpg",
    bestSeller: true,
  },
  {
    id: "8626",
    tab: "Burgers",
    description: "CB classic chicken burger",
    descriptionAlt: "برغر — CB classic chicken burger",
    extended: "",
    price: 2800,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_12838_1747214619809.jpg",
  },
  {
    id: "9532",
    tab: "Burgers",
    description: "Chicken Chapli Bun Kebab",
    descriptionAlt: "برغر — Chicken Chapli Bun Kebab",
    extended: "",
    price: 2600,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_14837.jpg",
  },
  {
    id: "2332",
    tab: "Juices",
    description: "Regular Watermelon Juice",
    descriptionAlt: "عصير — Regular Watermelon Juice",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan", "sugar_free"],
    image: "https://assets.voxcinemas.com/concessions/eaf580dd-3efd-400e-8898-ca66643cb5a2.jpg",
  },
  {
    id: "7476",
    tab: "Juices",
    description: "Chocolate Ice Cream Milkshake",
    descriptionAlt: "عصير — Chocolate Ice Cream Milkshake",
    extended: "",
    price: 3800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_10695_1743074066441.png",
  },
  {
    id: "2432",
    tab: "Juices",
    description: "Regular Orange Juice",
    descriptionAlt: "عصير — Regular Orange Juice",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_4012.jpg",
  },
  {
    id: "11176",
    tab: "Juices",
    description: "Mango Frappe",
    descriptionAlt: "عصير — Mango Frappe",
    extended: "",
    price: 2800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_17103_1756807907151.png",
  },
  {
    id: "7477",
    tab: "Juices",
    description: "Strawberry Ice Cream Milkshake",
    descriptionAlt: "عصير — Strawberry Ice Cream Milkshake",
    extended: "",
    price: 3800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_10697_1743074851637.png",
  },
  {
    id: "11175",
    tab: "Juices",
    description: "Caramel Coffee Frappe",
    descriptionAlt: "عصير — Caramel Coffee Frappe",
    extended: "",
    price: 2800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_17102_1756807927661.png",
  },
  {
    id: "2330",
    tab: "Juices",
    description: "Regular Pineapple Juice",
    descriptionAlt: "عصير — Regular Pineapple Juice",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/C_4013.jpg",
  },
  {
    id: "11174",
    tab: "Juices",
    description: "Coffee Frappe",
    descriptionAlt: "عصير — Coffee Frappe",
    extended: "",
    price: 2800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_17101_1756807947662.png",
  },
  {
    id: "2930",
    tab: "Juices",
    description: "Vanilla ice cream milkshake",
    descriptionAlt: "عصير — Vanilla ice cream milkshake",
    extended: "",
    price: 3800,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4472_1743074974177.png",
  },
  {
    id: "2474",
    tab: "Juices",
    description: "Regular Apple Juice",
    descriptionAlt: "عصير — Regular Apple Juice",
    extended: "",
    price: 2300,
    dietary: ["vegetarian", "vegan"],
    image: "https://assets.voxcinemas.com/concessions/9e3b4c30-07e9-4ea6-85d0-09e7e0b94872.jpg",
  },
  {
    id: "2420",
    tab: "Dessert",
    description: "Crepe Nutella",
    descriptionAlt: "حلويات — Crepe Nutella",
    extended: "",
    price: 2500,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3997_1743074754723.png",
  },
  {
    id: "9531",
    tab: "Dessert",
    description: "Churros Nutella Dip",
    descriptionAlt: "حلويات — Churros Nutella Dip",
    extended: "",
    price: 2300,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_14836_1743074599141.png",
  },
  {
    id: "2426",
    tab: "Dessert",
    description: "Extra Banana for Crepe",
    descriptionAlt: "حلويات — Extra Banana for Crepe",
    extended: "",
    price: 300,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4000.jpg",
  },
  {
    id: "2457",
    tab: "Dessert",
    description: "Extra Strawberry for Crepe",
    descriptionAlt: "حلويات — Extra Strawberry for Crepe",
    extended: "",
    price: 300,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4002.jpg",
  },
  {
    id: "3157",
    tab: "Dessert",
    description: "Ice Cream Cups",
    descriptionAlt: "حلويات — Ice Cream Cups",
    extended: "",
    price: 1600,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_514_1751347434321.jpg",
  },
  {
    id: "2305",
    tab: "Chocolates",
    description: "Snickers Bar",
    descriptionAlt: "شوكولاتة — Snickers Bar",
    extended: "",
    price: 900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3617.jpg",
  },
  {
    id: "2306",
    tab: "Chocolates",
    description: "Twix bar",
    descriptionAlt: "شوكولاتة — Twix bar",
    extended: "",
    price: 900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3618.jpg",
  },
  {
    id: "2270",
    tab: "Chocolates",
    description: "Mars Bar",
    descriptionAlt: "شوكولاتة — Mars Bar",
    extended: "",
    price: 900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4025.jpg",
  },
  {
    id: "3065",
    tab: "Chocolates",
    description: "Sweet Lollies Big",
    descriptionAlt: "شوكولاتة — Sweet Lollies Big",
    extended: "",
    price: 3700,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_4882.jpg",
  },
  {
    id: "2304",
    tab: "Chocolates",
    description: "M&M chocolate large",
    descriptionAlt: "شوكولاتة — M&M chocolate large",
    extended: "",
    price: 2900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3616.jpg",
  },
  {
    id: "2301",
    tab: "Chocolates",
    description: "Bounty bar",
    descriptionAlt: "شوكولاتة — Bounty bar",
    extended: "",
    price: 900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3613.jpg",
  },
  {
    id: "2302",
    tab: "Chocolates",
    description: "Galaxy bar",
    descriptionAlt: "شوكولاتة — Galaxy bar",
    extended: "",
    price: 900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3614.jpg",
  },
  {
    id: "2303",
    tab: "Chocolates",
    description: "M&M Peanut Large",
    descriptionAlt: "شوكولاتة — M&M Peanut Large",
    extended: "",
    price: 2900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3615.jpg",
  },
  {
    id: "2249",
    tab: "Chocolates",
    description: "Maltesers large",
    descriptionAlt: "شوكولاتة — Maltesers large",
    extended: "",
    price: 2900,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_3619.jpg",
  },
  {
    id: "7765",
    tab: "Chocolates",
    description: "Yum yum lollipop",
    descriptionAlt: "شوكولاتة — Yum yum lollipop",
    extended: "",
    price: 1000,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_10781.jpg",
  },
  {
    id: "4780",
    tab: "Extra",
    description: "3D Glasses Kids",
    descriptionAlt: "إضافات — 3D Glasses Kids",
    extended: "",
    price: 300,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_6421.jpg",
  },
  {
    id: "972",
    tab: "Snacks",
    description: "Potato Chips Classic Salted",
    descriptionAlt: "سناك — Potato Chips Classic Salted",
    extended: "",
    price: 500,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_1649_1727699675577.jpeg",
  },
  {
    id: "8686",
    tab: "Snacks",
    description: "Haldirams moong dal",
    descriptionAlt: "سناك — Haldirams moong dal",
    extended: "",
    price: 700,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_12967.jpg",
  },
  {
    id: "8684",
    tab: "Snacks",
    description: "Ding dong mixed nuts hot and spicy",
    descriptionAlt: "سناك — Ding dong mixed nuts hot and spicy",
    extended: "",
    price: 1000,
    dietary: ["vegetarian", "gluten_free", "spicy"],
    image: "https://assets.voxcinemas.com/concessions/C_12965.jpg",
  },
  {
    id: "5748",
    tab: "Snacks",
    description: "Ding dong mix nuts orange",
    descriptionAlt: "سناك — Ding dong mix nuts orange",
    extended: "",
    price: 1000,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_6855.jpg",
  },
  {
    id: "8685",
    tab: "Snacks",
    description: "Haldirams nut cracker",
    descriptionAlt: "سناك — Haldirams nut cracker",
    extended: "",
    price: 700,
    dietary: ["vegetarian"],
    image: "https://assets.voxcinemas.com/concessions/C_12966.jpg",
  },
  {
    id: "3386",
    tab: "Snacks",
    description: "Potato Chips Pudina Treat",
    descriptionAlt: "سناك — Potato Chips Pudina Treat",
    extended: "",
    price: 500,
    dietary: ["vegetarian", "gluten_free"],
    image: "https://assets.voxcinemas.com/concessions/C_1506_1727699702457.jpeg",
  },
  {
    id: "11870",
    tab: "Pass",
    description: "Entertainment Pass 129 AED",
    descriptionAlt: "باس — Entertainment Pass 129 AED",
    extended: "",
    price: 12900,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_18207_1786962075606.jpg",
  },
  {
    id: "11868",
    tab: "Pass",
    description: "Entertainment Pass 149 AED",
    descriptionAlt: "باس — Entertainment Pass 149 AED",
    extended: "",
    price: 14900,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_18205_1786962026810.jpg",
  },
  {
    id: "11869",
    tab: "Pass",
    description: "Entertainment Pass 229 AED",
    descriptionAlt: "باس — Entertainment Pass 229 AED",
    extended: "",
    price: 22900,
    dietary: [],
    image: "https://assets.voxcinemas.com/concessions/C_18206_1786962057114.jpg",
  },
  {
    id: "170",
    tab: "GOLD Menu",
    description: "GOLD Wagyu Sliders",
    descriptionAlt: "سلايدرز واغيو غولد",
    extended: "Three wagyu sliders with truffle fries, served to your seat.",
    price: 8900,
    dietary: [],
    allergens: ["gluten", "milk"],
    calories: 880,
    experiences: ["GOLD", "THEATRE"],
    image: "https://assets.voxcinemas.com/content/Burgers_1786348870.jpg",
  },
  {
    id: "171",
    tab: "GOLD Menu",
    description: "GOLD Truffle Mushroom Pasta",
    descriptionAlt: "باستا فطر بالكمأة",
    extended: "Fresh tagliatelle, wild mushrooms, parmesan.",
    price: 7900,
    dietary: ["vegetarian", "contains_dairy"],
    allergens: ["gluten", "milk"],
    calories: 720,
    experiences: ["GOLD", "THEATRE"],
    image: "https://assets.voxcinemas.com/content/Wraps_1786349043.jpg",
  },
  {
    id: "172",
    tab: "GOLD Menu",
    description: "GOLD Mezze Platter",
    descriptionAlt: "طبق مقبلات غولد",
    extended: "Hummus, moutabal, tabbouleh, warm bread — plant-based.",
    price: 6500,
    dietary: ["vegetarian", "vegan"],
    allergens: ["gluten", "sesame"],
    calories: 540,
    experiences: ["GOLD", "THEATRE"],
    image: "https://assets.voxcinemas.com/content/Sweet_nachos_1787038927.jpg",
  },
  {
    id: "173",
    tab: "GOLD Menu",
    description: "GOLD Mocktail",
    descriptionAlt: "موكتيل غولد",
    extended: "Passion fruit & mint cooler.",
    price: 3200,
    dietary: ["vegan", "gluten_free"],
    calories: 150,
    experiences: ["GOLD", "THEATRE"],
    image: "https://assets.voxcinemas.com/concessions/C_4751_1783926996639.jpg",
  },
];

export type OfferSpec = {
  id: string;
  title: string;
  titleAlt: string;
  short: string;
  shortAlt: string;
  terms: string;
  type: "bank" | "promo" | "loyalty" | "member" | "partner";
  rules: OfferRules;
  benefit: OfferBenefit;
  budget?: number;
  perMember?: number;
  howToRedeem: string;
  priority: number;
  /** Banner/logo — real assets from uae.voxcinemas.com where available. */
  image?: string;
};

const LOGO = (f: string) => `https://assets.voxcinemas.com/offers/${f}`;
const BANNER = (f: string) => `https://assets.voxcinemas.com/content/${f}`;

export const OFFERS: OfferSpec[] = [
  {
    id: "BANK-ADCB-BOGO",
    image: BANNER("ADCB_1715028023.jpg"),
    title: "ADCB – Buy One Get One",
    titleAlt: "بنك أبوظبي التجاري – اشترِ تذكرة واحصل على أخرى",
    short: "Buy one ticket, get one free with your ADCB credit card.",
    shortAlt: "اشترِ تذكرة واحصل على الثانية مجاناً ببطاقة ADCB الائتمانية.",
    terms:
      "Valid on Standard and MAX sessions, Sunday–Wednesday. Max 2 free tickets per card per month. Tickets purchased with bank offers are non-refundable.",
    type: "bank",
    rules: {
      experiences: ["Standard", "MAX"],
      days: [0, 1, 2, 3],
      bankBins: ["409255", "415732"],
      bankName: "ADCB",
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 2,
      maxTicketsPerRedemption: 4,
      minTickets: 2,
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    perMember: 2,
    howToRedeem: "Pay with an eligible ADCB credit card at checkout; the discount is applied automatically.",
    priority: 10,
  },
  {
    id: "BANK-ENBD-BOGO",
    image: BANNER("enbd_Banner_1736316179.jpg"),
    title: "Emirates NBD – Buy One Get One",
    titleAlt: "بنك الإمارات دبي الوطني – اشترِ تذكرة واحصل على أخرى",
    short: "Buy one, get one free on all experiences with Emirates NBD credit cards.",
    shortAlt: "اشترِ واحدة واحصل على الثانية مجاناً على جميع التجارب ببطاقات الإمارات دبي الوطني.",
    terms: "Valid every day except public holidays. Excludes Private cinemas. Non-refundable.",
    type: "bank",
    rules: {
      bankBins: ["455533", "521334"],
      bankName: "Emirates NBD",
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 3,
      maxTicketsPerRedemption: 2,
      minTickets: 2,
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    howToRedeem: "Pay with an Emirates NBD credit card.",
    priority: 11,
  },
  {
    id: "BANK-HSBC-BOGO-FNB",
    image: BANNER("Banners-for-web_1000x270-eng_1723630263.jpg"),
    title: "HSBC – BOGO + 25% off F&B",
    titleAlt: "HSBC – تذكرة مجانية وخصم 25% على المأكولات",
    short: "Buy one get one free, plus 25% off food and drinks with HSBC credit cards.",
    shortAlt: "اشترِ تذكرة واحصل على أخرى مجاناً، مع خصم 25% على الطعام والمشروبات.",
    terms: "Thursday to Saturday. F&B discount applies to items added to the same order.",
    type: "bank",
    rules: {
      days: [4, 5, 6],
      bankBins: ["424141"],
      bankName: "HSBC",
      minTickets: 2,
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 2,
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    howToRedeem: "Pay with an HSBC credit card.",
    priority: 12,
  },
  {
    id: "BANK-CBD-50",
    image: LOGO("O_CBD.png"),
    title: "Commercial Bank of Dubai – 50% off",
    titleAlt: "بنك دبي التجاري – خصم 50%",
    short: "50% off movie tickets with CBD credit cards.",
    shortAlt: "خصم 50% على تذاكر السينما ببطاقات بنك دبي التجاري.",
    terms: "Up to 4 tickets per transaction. Standard and Premier only.",
    type: "bank",
    rules: {
      experiences: ["Standard", "Premier"],
      bankBins: ["437745"],
      cardDigits: { first: 8, last: 4 },
      monthlyLimit: 2,
      bankName: "CBD",
      maxTicketsPerRedemption: 4,
    },
    benefit: { type: "percent_off", percent: 50, appliesTo: "tickets" },
    howToRedeem: "Pay with a CBD credit card.",
    priority: 13,
  },
  {
    id: "BANK-MASHREQ-50",
    image: LOGO("O_Mashreq.jpg"),
    title: "Mashreq – 50% off",
    titleAlt: "المشرق – خصم 50%",
    short: "50% off movie tickets with selected Mashreq credit cards.",
    shortAlt: "خصم 50% على التذاكر ببطاقات المشرق المختارة.",
    terms: "Valid Sunday–Thursday. Max 2 tickets.",
    type: "bank",
    rules: {
      days: [0, 1, 2, 3, 4, 5, 6],
      bankBins: ["472937"],
      bankName: "Mashreq",
      maxTicketsPerRedemption: 2,
      cardDigits: { first: 8, last: 4 },
      monthlyLimit: 2,
    },
    benefit: { type: "percent_off", percent: 50, appliesTo: "tickets" },
    howToRedeem: "Pay with a Mashreq credit card.",
    priority: 14,
  },
  {
    id: "BANK-CITI-30",
    image: LOGO("O_citi30.jpg"),
    title: "Citi – 30% off tickets",
    titleAlt: "سيتي بنك – خصم 30٪ على التذاكر",
    short: "30% off movie tickets with selected Citi credit cards, any day.",
    shortAlt: "خصم 30٪ على تذاكر السينما ببطاقات سيتي الائتمانية المختارة.",
    terms:
      "Selected Citi credit cards. Up to 2 tickets per card per month. Verify the first 7 and last 4 digits of your card at checkout and pay with the same card. Non-refundable.",
    type: "bank",
    rules: {
      bankBins: ["4288", "5426"],
      bankName: "Citi",
      maxTicketsPerRedemption: 2,
      cardDigits: { first: 7, last: 4 },
      monthlyLimit: 2,
    },
    benefit: { type: "percent_off", percent: 30, appliesTo: "tickets" },
    howToRedeem: "Choose Citi under Bank Offers, verify your card digits and pay with that card.",
    priority: 15,
  },
  {
    id: "BANK-RAK-50",
    image: LOGO("O_RAK.jpg"),
    title: "RAKBANK – 50% off tickets",
    titleAlt: "راك بنك – خصم 50٪ على التذاكر",
    short: "50% off all movie tickets with your RAKBANK World credit card.",
    shortAlt: "خصم 50٪ على جميع تذاكر السينما ببطاقة راك بنك وورلد الائتمانية.",
    terms:
      "RAKBANK World credit cards. Up to 2 tickets per card per month. Verify the first 6 and last 4 digits at checkout. Non-refundable.",
    type: "bank",
    rules: {
      bankBins: ["401836"],
      bankName: "RAKBANK",
      maxTicketsPerRedemption: 2,
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 2,
    },
    benefit: { type: "percent_off", percent: 50, appliesTo: "tickets" },
    howToRedeem: "Choose RAKBANK under Bank Offers, verify your card digits and pay with that card.",
    priority: 16,
  },
  {
    id: "BANK-FAB-WEEKEND",
    image: LOGO("O_FAB.jpg"),
    title: "FAB – Weekend buy one get one",
    titleAlt: "بنك أبوظبي الأول – اشترِ واحدة واحصل على أخرى في عطلة الأسبوع",
    short: "Buy one ticket, get one free on Fridays and Saturdays with FAB credit cards.",
    shortAlt: "اشترِ تذكرة واحصل على الثانية مجاناً يومي الجمعة والسبت ببطاقات بنك أبوظبي الأول.",
    terms:
      "FAB credit cards, Fridays and Saturdays. 2 free tickets per card per month. Verify the first 6 and last 4 digits at checkout. Non-refundable.",
    type: "bank",
    rules: {
      days: [5, 6],
      bankBins: ["417930", "516320"],
      bankName: "FAB",
      minTickets: 2,
      maxTicketsPerRedemption: 2,
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 2,
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    howToRedeem: "Choose FAB under Bank Offers, verify your card digits and pay with that card.",
    priority: 17,
  },
  {
    id: "BANK-SCB-BOGO",
    image: BANNER("STD-1000x270_1786964774.png"),
    title: "Standard Chartered – free ticket for every ticket",
    titleAlt: "ستاندرد تشارترد – تذكرة مجانية مع كل تذكرة",
    short: "A free ticket for every ticket you buy with a Standard Chartered credit card.",
    shortAlt: "تذكرة مجانية مع كل تذكرة تشتريها ببطاقة ستاندرد تشارترد الائتمانية.",
    terms:
      "Standard Chartered credit cards. Up to 3 free tickets per card per month. Verify the first 6 and last 4 digits at checkout. Non-refundable.",
    type: "bank",
    rules: {
      bankBins: ["490118"],
      bankName: "Standard Chartered",
      minTickets: 2,
      cardDigits: { first: 6, last: 4 },
      monthlyLimit: 3,
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    howToRedeem:
      "Choose Standard Chartered under Bank Offers, verify your card digits and pay with that card.",
    priority: 18,
  },
  {
    id: "FORYOU-BOGO",
    image:
      "https://cdn-ent-prod-campaignassets.voxcinemas.org/345x320_daa8675a-3b2a-4439-a6bb-3ae2a29073fc.jpg",
    title: "For you: Buy 1 get 1 free",
    titleAlt: "لك: اشترِ تذكرة واحصل على أخرى مجاناً",
    short:
      "We can't wait to welcome you back to VOX Cinemas! Book online and enjoy two tickets for the price of one.",
    shortAlt: "احجز عبر الإنترنت واستمتع بتذكرتين بسعر تذكرة واحدة.",
    terms: "Personal member offer, one redemption. Standard sessions. Valid until 15 December.",
    type: "member",
    rules: {
      membersOnly: true,
      experiences: ["Standard"],
      minTickets: 2,
      maxTicketsPerRedemption: 2,
      validTo: "2026-12-15",
    },
    benefit: { type: "bogo", buy: 1, get: 1 },
    perMember: 1,
    howToRedeem: "Log in — the offer appears under My Offers and applies at checkout.",
    priority: 19,
  },
  {
    id: "VOX-JUNIOR-CLUB",
    image: BANNER("Junior_Club_1715027903.jpg"),
    title: "Junior Club – AED 25 tickets",
    titleAlt: "نادي الصغار – تذاكر بـ 25 درهماً",
    short: "AED 25 tickets for re-releases at VOX KIDS every Friday, Saturday & Sunday.",
    shortAlt: "تذاكر بـ 25 درهماً لعروض الأطفال المعادة في VOX KIDS كل جمعة وسبت وأحد.",
    terms: "KIDS experience only, weekends.",
    type: "promo",
    rules: { experiences: ["KIDS"], days: [5, 6, 0] },
    benefit: { type: "fixed_price_cents", priceCents: 2500, appliesTo: "tickets" },
    howToRedeem: "Select a KIDS weekend session; the price is applied automatically.",
    priority: 20,
  },
  {
    id: "PROMO-MOVIEMONDAY",
    image: BANNER("VOX_Cinemas__Offer_Page_Banner_1735553285.jpg"),
    title: "Movie Monday – 30% off",
    titleAlt: "الاثنين السينمائي – خصم 30%",
    short: "30% off Standard tickets every Monday with code MONDAY30.",
    shortAlt: "خصم 30% على التذاكر العادية كل اثنين برمز MONDAY30.",
    terms: "Online only. Not combinable with bank offers.",
    type: "promo",
    rules: { experiences: ["Standard"], days: [1], promoCode: "MONDAY30" },
    benefit: { type: "percent_off", percent: 30, appliesTo: "tickets" },
    budget: 500,
    howToRedeem: "Enter promo code MONDAY30 at checkout.",
    priority: 21,
  },
  {
    id: "PROMO-FNB-COMBO10",
    image: BANNER("Summer_combo_beat_the_heat_1-1_1785851137.png"),
    title: "AED 10 off any combo",
    titleAlt: "خصم 10 دراهم على أي كومبو",
    short: "AED 10 off any combo when added to your ticket order.",
    shortAlt: "خصم 10 دراهم على أي كومبو عند إضافته لطلب التذاكر.",
    terms: "One per order.",
    type: "promo",
    rules: {},
    benefit: { type: "amount_off_cents", amountCents: 1000, appliesTo: "concessions" },
    howToRedeem: "Add a combo to your order; the discount applies automatically.",
    priority: 30,
  },
  {
    id: "SHARE-MEMBER-10",
    image: BANNER("FAB_SHARE_VOX_1000_1786440840.png"),
    title: "SHARE members save 10%",
    titleAlt: "أعضاء شير يوفرون 10%",
    short: "Logged-in SHARE members get 10% off tickets and earn Share Points on every purchase.",
    shortAlt: "أعضاء شير المسجلون يحصلون على خصم 10% ويكسبون نقاط شير مع كل عملية شراء.",
    terms: "Members only.",
    type: "member",
    rules: { membersOnly: true },
    benefit: { type: "percent_off", percent: 10, appliesTo: "tickets" },
    howToRedeem: "Log in with your SHARE account before paying.",
    priority: 40,
  },
  {
    id: "SHARE-DOUBLE-POINTS",
    image: BANNER("FAB_SHARE_VOX_1000_1786440840.png"),
    title: "Double Share Points on GOLD",
    titleAlt: "نقاط شير مضاعفة على غولد",
    short: "Earn 2x Share Points on GOLD and THEATRE bookings this month.",
    shortAlt: "اكسب نقاط شير مضاعفة على حجوزات غولد وثياتر هذا الشهر.",
    terms: "Members only. Gold and Platinum tiers.",
    type: "loyalty",
    rules: { membersOnly: true, experiences: ["GOLD", "THEATRE"], tiers: ["Gold", "Platinum"] },
    benefit: { type: "points_multiplier", multiplier: 2 },
    howToRedeem: "Automatic for eligible members.",
    priority: 41,
  },
  {
    id: "PROMO-3DGLASSES",
    image: BANNER("1000x270_1746624137.jpg"),
    title: "Free 3D glasses",
    titleAlt: "نظارات 3D مجانية",
    short: "Free 3D glasses with any IMAX ticket.",
    shortAlt: "نظارات 3D مجانية مع أي تذكرة آيماكس.",
    terms: "IMAX 3D sessions only.",
    type: "promo",
    rules: { experiences: ["IMAX"] },
    benefit: { type: "free_item", itemId: "4780" },
    howToRedeem: "Automatic.",
    priority: 50,
  },
];

/** Per-cinema extensions (in-mall directions, parking, hours, accessibility). Dummy where not on the website. */
export const CINEMA_EXTRAS: Record<
  string,
  {
    directions: string;
    directionsAlt: string;
    parking: string;
    accessibility: string;
    hours?: [string, string];
  }
> = {
  "0002": {
    directions:
      "Take the escalators to Level 2 next to Ski Dubai's viewing gallery; VOX is opposite the Kempinski entrance. From the Carrefour side, follow the signs to 'Cinema'.",
    directionsAlt: "اصعد بالسلالم المتحركة إلى الطابق الثاني بجوار سكي دبي؛ فوكس مقابل مدخل كمبينسكي.",
    parking:
      "Park in the East car park (Level 2) – it is the closest to the cinema entrance. Valet is available at the Kempinski entrance.",
    accessibility:
      "Step-free access via lifts by the East car park; wheelchair seats in every screen; accessible restrooms next to the ticket desk.",
  },
  "0001": {
    directions:
      "VOX is on Level 2 above the food court. Take the lifts near Carrefour or the escalators from the central atrium.",
    directionsAlt: "فوكس في الطابق الثاني فوق منطقة المطاعم. استخدم المصاعد قرب كارفور.",
    parking: "Level 2 parking (P2) has a direct walkway to the cinema.",
    accessibility:
      "Lift access from all parking levels; wheelchair-accessible seating; hearing-loop available at GOLD.",
  },
  "0005": {
    directions: "Located on Level 2 at the Ghurair end of the mall next to Magic Planet.",
    directionsAlt: "في الطابق الثاني بجوار ماجيك بلانيت.",
    parking: "Use the P2 Blue car park entrance from Tripoli Street.",
    accessibility: "Step-free access; wheelchair seats available in all screens.",
  },
  "0046": {
    directions:
      "VOX is on the 4th level of The Galleria, above the luxury wing. Take the lifts from the ADGM Square entrance.",
    directionsAlt: "فوكس في الطابق الرابع من الغاليريا فوق الجناح الفاخر.",
    parking: "Basement parking B2 is closest to the cinema lifts; 3 hours free with validation.",
    accessibility: "Fully step-free; accessible seating in IMAX, THEATRE and KIDS.",
  },
  "0012": {
    directions:
      "Level 2, next to the food court. From the main entrance, take the escalators up twice and turn right.",
    directionsAlt: "الطابق الثاني بجوار منطقة المطاعم.",
    parking: "North car park Level 2 – closest to the cinema entrance.",
    accessibility: "Step-free access; wheelchair seating; companion seats available.",
  },
  "0049": {
    directions:
      "VOX is on Level 3 (top floor) of Nakheel Mall. Take the panoramic lifts from the Palm Monorail entrance.",
    directionsAlt: "فوكس في الطابق الثالث من نخيل مول.",
    parking: "Level 3 parking connects directly to the cinema foyer.",
    accessibility: "Step-free access; wheelchair seats in every screen.",
  },
};

export const DEFAULT_EXTRA = (cinemaLocation: string, parking: string) => ({
  directions: cinemaLocation
    ? `The cinema is located on ${cinemaLocation.replace(/^Located on\s*/i, "")}. Follow the 'VOX Cinemas' signs from the main atrium or ask at the mall information desk.`
    : "Follow the 'VOX Cinemas' signs from the main atrium or ask at the mall information desk.",
  directionsAlt: cinemaLocation
    ? `تقع السينما في ${cinemaLocation}. اتبع لافتات فوكس سينما من البهو الرئيسي.`
    : "اتبع لافتات فوكس سينما من البهو الرئيسي.",
  parking: parking
    ? `Nearest parking: ${parking}.`
    : "Use the mall car park closest to the cinema entrance; parking is free for cinema guests.",
  accessibility:
    "Step-free access via mall lifts; wheelchair-accessible seating available in every screen (please ask staff for assistance); accessible restrooms nearby.",
});

export const AGE_RULES = [
  { rating: "G", minAge: 0, text: "Suitable for all ages." },
  {
    rating: "PG",
    minAge: 0,
    text: "Parental guidance advised. Some material may not be suitable for children.",
  },
  {
    rating: "PG13",
    minAge: 0,
    text: "Guests aged 13 and under may attend but must be accompanied by someone aged 13 or older.",
  },
  {
    rating: "PG15",
    minAge: 0,
    text: "Guests aged 15 and under may attend but must be accompanied by someone aged 15 or older.",
  },
  {
    rating: "15+",
    minAge: 15,
    text: "No persons under 15 will be admitted. ID required. Infants not allowed.",
  },
  {
    rating: "18+",
    minAge: 18,
    text: "No persons under 18 will be admitted. ID required. Infants not allowed.",
  },
  {
    rating: "18TC",
    minAge: 18,
    text: "Provisionally rated 18+ pending final classification. Tickets are non-refundable.",
  },
  { rating: "21+", minAge: 21, text: "No persons under 21 will be admitted. ID required." },
];

export const EXPERIENCE_AGE_RULES: Record<string, string> = {
  GOLD: "GOLD is an adults-first experience: guests must be 18+ except at Mall of the Emirates, City Centre Mirdif and Yas Mall where children 8+ are welcome with an adult.",
  THEATRE: "THEATRE welcomes guests 18+ only.",
  KIDS: "KIDS screens are designed for children; adults must be accompanied by a child (booster seats available).",
  "4DX":
    "4DX: minimum height 100 cm; not recommended for pregnant guests or guests with heart or back conditions.",
  Private: "Private cinemas: booker must be 21+.",
};
